### ISSUE TITLE
add option for tight packing encoding

### ISSUE THREAD

**Issue by ralexstokes** [MariusVanDerWijden/blob-me-baby#5]
it looks like the current encoding leaves every 32nd byte empty, which is a valid way to pack but there are a few bits we are missing that we _could_ be using

the tricky bit is that you have to consider each 256 bits of the data and keep it under the modulus of the BLS12-381 field

but it should be possible to achieve a tighter packing than what we have now

**Comment by asn-d6** [comment]
FWIW, I coded a tight packer some time ago using rust's excellent bitvec crate, that can pack 254 bits per 32 bytes: https://github.com/asn-d6/blobbers/blob/main/src/packer_tight.rs

**Comment by MariusVanDerWijden** [comment]
closed by https://github.com/MariusVanDerWijden/blob-me-baby/pull/8
